version: '3'
services:
  app:
    build: .
    links:
      - redis
      - memcached
    volumes:
      - .:/app/
  redis:
    image: redis
  redis2:
    image: redis
  redis3:
    image: redis
  memcached:
    image: memcached
